title: Cho Do Hyoung Blog
description: My Personal Blog.[Cho Do Hyoung]
author: Cho Do Hyoung
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/ChoDoHyoung/chodohyoung.github.io
about: Full stack developer

baseurl: ""
url: "https://chodohyoung.github.io/"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
